### ISSUE TITLE
Add staff page

### ISSUE THREAD

**Issue by Palmidence** [WarzoneMC/website#23]
This has been put on hold for now until the API is restructured to have staff ranks recorded in the backend. The staff page would pull from the API and sort staff on the website by including:

- The rank that they are (e.g. BennyDoesStuff - Moderator)
- The role that they serve (e.g. Teejers -> Map Management)
- The Minecraft head including top layer of their skin (viable API - [Minotar](https://minotar.net/))

It would be sorted into sections, such as `Administrators`, `Developers`, `Moderators`, and any further staff ranks that are included. These would be colored accordingly with what they are on Discord and in-game.

This would also be put into the footer of the site.

**Comment by Synconix** [comment]
Yea nice suggestion, I might add this

**Comment by SmockSmock** [comment]
You have no idea how to code anyway, lmao.

**Comment by LewisP2018** [comment]
Sounds good

**Comment by RileyDatLord** [comment]
Not doing this for advertisement purposes, but maybe you could do it like me (I have categories, but I choose not to use them as it clumps the page up more) [My Website](http://anvilmh.party/#staff) and also plox no one (Draem) complain about me using php.

**Comment by LewisP2018** [comment]
@RileyDatLord Looks really good
