### ISSUE TITLE
Images in about page don't work

### ISSUE THREAD

**Issue by JapaneseSquid** [WarzoneMC/Website#39]
The images don't show up. Only the link, although when you're editing the profile the links show up green as if it's supposed to work.
https://warzone.network/u/KyotoSquid for reference.
It is possible that this issue is exclusive to me, but anyway
/shrug

**Comment by jorgeberrex** [comment]
Try this on your profile
```
![Image text](https://i.imgur.com/GGu6OEB.png)
```

**Comment by JapaneseSquid** [comment]
Ohhhhhh I see now.
