### ISSUE TITLE
Map Egypt yellow wool doesnt work right

### ISSUE THREAD

**Issue by lefckntea** [WarzoneMC/Website#46]
Many of the yellow wool blocks ([DTW] Egypt) dont work.
Some work but its not enough to get 100% so its impossible to win.

**Comment by BennyDoesTheStuff** [comment]
Why are you making an issue here ???

**Comment by lefckntea** [comment]
wdym

**Comment by BennyDoesTheStuff** [comment]
"Website" repo, close this issue and put on correct repo

**Comment by lefckntea** [comment]
oh sorry
