### ISSUE TITLE
Use WebP for images

### ISSUE THREAD

**Issue by jellz** [WarzoneMC/website#61]
WebP is faster than JPG and PNG.

The following images should be converted:
- https://i.imgur.com/ozg7teT.png
- https://i.imgur.com/0N5yGOV.png
- https://i.imgur.com/DnobRWZ.png
- https://i.imgur.com/rMB613Q.png
- https://i.imgur.com/Sc5Gkkn.jpg

**Comment by RONTheCookie** [comment]
I'm gonna do it soon

**Comment by TheRealPear** [comment]
Only problem is that it doesn't work on Edge, even with fallback images.

**Comment by Draem** [comment]
microsoft added support for webp on edge

**Comment by TheRealPear** [comment]
> 
> 
> microsoft added support for webp on edge 18

Never mind then. I read somewhere that Edge didn't like webp images, but I guess that got fixed or something.

**Comment by RONTheCookie** [comment]
Done, GitHub doesn't support tar.xz so here's a link: [webpjellzwz.tar.xz](https://i.ronthecookie.me/webpjellzwz.tar.xz)

**Comment by jellz** [comment]
Thanks @RONTheCookie!

**Comment by jellz** [comment]
This was added in the following commits:
- 5bc95628818529e6f7e376e1081a74488337d1da
- 033baa1238c39f424b42be2b9c9fe92f7c69e5c1
- 90cce0c474fd1d059cc1307c31dc3a1c22d7b11f
- 2284d7c6d064573c06af179823127b205b8f5281
